AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for aws-dotnet-textract

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod


Globals:
  # Global attributes for each function
  Function:
    Timeout: 10
    Runtime: dotnet6
    MemorySize: 256
    Architectures:
      - arm64



Resources:
#Functions
  SendToTextract:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SendToTextract
      CodeUri: ./src/ServerlessTextToSpeech.SendToTextract
      Handler: ServerlessTextToSpeech.SendToTextract
  PublishMetaData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PublishMetaData
      CodeUri: ./src/ServerlessTextToSpeech.PublishMetaData
      Handler: ServerlessTextToSpeech.PublishMetaData
  ProcessText:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProcessText
      CodeUri: ./src/ServerlessTextToSpeech.ProcessText
      Handler: ServerlessTextToSpeech.ProcessText

#S3 buckets
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", ["serverles-source-data", !Ref Environment]]
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", ["serverless-output-data", !Ref Environment]]
#Database
  MetaDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Join ["-", ["serverless_data", !Ref Environment]]

#Step Function and related data
  ProcessStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:

      Name: "TextToSpeechStateMachine"
      Type: STANDARD
      DefinitionUri: ./statemachine.asl.yaml
      DefinitionSubstitutions:
        SendToTextractFunction: !GetAtt SendToTextract.Arn
        PublishMetadataFunction: !GetAtt PublishMetaData.Arn
        ProcessTextFunction: !GetAtt ProcessText.Arn
      Role: !Ref StateMachineRole.Arn
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", ["stepfunction-role", !Ref Environment]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - !Ref SourceBucket.Arn
              - !Ref PublishMetaData.Arn
              ` !Ref ProcessText.Arn
                  
          PolicyName: LambdaExecution






